server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowerSpot
    username: root
    password: vloriberisha
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: validate
        hbm2ddl: validate
jwt:
  secret: PurkmRDAnAaSvmDaAfi
quote:
  api:
    link: http://quotes.rest/qod